name: "Reporte de bug"
description: "Informar un error en Toca Toca."
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar. Cuanto más concreto sea el reporte, más rápido se puede resolver.
  - type: textarea
    id: descripcion_problema
    attributes:
      label: Descripción del problema
      description: Contá claramente qué está fallando.
      placeholder: Al girar la ruleta, el resultado se congela...
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      description: Indica una secuencia corta para repetir el problema.
      placeholder: |
        1. Abrir la app
        2. Configurar X
        3. Hacer clic en Y
        4. Ver error
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Resultado esperado
      description: ¿Qué debería pasar?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
      description: ¿Qué pasa realmente?
    validations:
      required: true
  - type: dropdown
    id: impacto
    attributes:
      label: Impacto
      description: ¿Qué tan grave es este bug?
      options:
        - Bloqueante (no puedo usar la app)
        - Alto (flujo principal afectado)
        - Medio (hay workaround)
        - Bajo (detalle menor)
    validations:
      required: true
  - type: dropdown
    id: entorno
    attributes:
      label: Entorno
      options:
        - Web (desktop)
        - Web (mobile)
        - Ambos
    validations:
      required: true
  - type: input
    id: navegador
    attributes:
      label: Navegador y versión
      description: "Ejemplo: Chrome 122, Safari 17.4"
      placeholder: Chrome 122
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Versión visible en la app
      description: "Ejemplo: v1.0.0"
      placeholder: v1.0.0
    validations:
      required: false
  - type: textarea
    id: evidencia
    attributes:
      label: Evidencia adicional (opcional)
      description: Capturas, video, consola o contexto técnico extra.
      placeholder: Pegá acá logs o detalles relevantes.
    validations:
      required: false
  - type: checkboxes
    id: privacidad
    attributes:
      label: Confirmación de privacidad
      options:
        - label: Entiendo que este issue es público y no incluye datos personales o sensibles.
          required: true
