name: "Propuesta de mejora"
description: "Sugerir una idea o funcionalidad para Toca Toca."
title: "[Idea]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Compartí la propuesta con foco en problema, valor y cómo validar el resultado.
  - type: textarea
    id: propuesta
    attributes:
      label: Propuesta
      description: Explicá la mejora que te gustaría ver.
      placeholder: Me gustaría sumar...
    validations:
      required: true
  - type: textarea
    id: problema_actual
    attributes:
      label: Problema actual
      description: ¿Qué fricción o necesidad concreta resuelve esta idea?
      placeholder: Hoy cuesta...
    validations:
      required: true
  - type: textarea
    id: beneficio_esperado
    attributes:
      label: Beneficio esperado
      description: ¿Qué valor aporta para quienes usan la app?
      placeholder: Esto ayudaría a...
    validations:
      required: true
  - type: textarea
    id: criterios_exito
    attributes:
      label: Criterios de éxito (opcional)
      description: ¿Cómo sabríamos que la mejora funcionó?
      placeholder: Se considera resuelto cuando...
    validations:
      required: false
  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas consideradas (opcional)
      description: Otras opciones evaluadas y por qué no alcanzan.
    validations:
      required: false
  - type: textarea
    id: contexto
    attributes:
      label: Contexto adicional (opcional)
      description: Ejemplos, capturas o detalles extra.
    validations:
      required: false
  - type: checkboxes
    id: privacidad
    attributes:
      label: Confirmación de privacidad
      options:
        - label: Entiendo que este issue es público y no incluye datos personales o sensibles.
          required: true
